image: node:10.15.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules
  - ${CYPRESS_CACHE_FOLDER}

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn install
    - yarn run lint

test:
  stage: test
  script:
    - yarn install
    - yarn run test-all

build development:
  stage: build
  script:
    - yarn install
    - yarn run build:development
  artifacts:
    expire_in: 1 week
    paths:
      - dist/development

deploy review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build development
  environment:
    name: $CI_BUILD_REF_NAME
    url: $BASE_REVIEW_URL/$CI_BUILD_REF_NAME
    on_stop: delete review
  script:
    - echo "Deploy a review app"
    - '[ -z "${DEPLOY_BASE_DIR}" ] && echo "Deploy base dir cannot be empty" && exit 255'
    - env
    - mkdir -p "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}"
    - echo "Copy dev build to web server ${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}..."
    - rsync --delete -va dist/development/ "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}/"
    - curl "https://api.telegram.org/bot699197118:AAGXNTaC5Q-ljmy_dMvaIvAKy1XjlkA3Iss/sendMessage?chat_id=-1001354778014&text=https://onboarding.sldev.cz/${CI_BUILD_REF_NAME}"
    - 'echo "Remove working dir, workaround for cache" && rm -r ./*'
  #only:
  #  - branches
  tags:
    - deploy

delete review:
  before_script: []
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: $CI_BUILD_REF_NAME
    action: stop
  script:
    - '[ -z "${DEPLOY_BASE_DIR}" ] && echo "Deploy dir can not be empty" && exit 1'
    - '[ -z "${CI_BUILD_REF_NAME}" ] && echo "Build name can not be empty" && exit 1'
    - '[ ! -d "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}" ] && echo "Folder can not be found, skipping..." && exit 0'
    - 'rm -r "${DEPLOY_BASE_DIR}/${CI_BUILD_REF_NAME}"'
  #only:
  #  - branches
  tags:
    - deploy
